collections:
- name: community.general
  version: 8.4.0
- name: kubernetes.core
  version: 3.0.1

roles:
  - name: ansible-role-rke2
    src: git+https://github.com/BlindfoldedSurgery/ansible-role-rke2.git
    version: main
  - name: ansible-role-cluster-baseconfig
    src: git+https://github.com/BlindfoldedSurgery/ansible-role-cluster-baseconfig.git
    version: main
  - name: ansible-role-os-baseconfig
    src: git+https://github.com/BlindfoldedSurgery/ansible-role-os-baseconfig.git
    version: main
