collections:
- name: community.general
  version: 8.1.0
- name: kubernetes.core
  version: 3.0.0

roles:
  - name: ansible-role-rke2
    src: git+git@github.com:BlindfoldedSurgery/ansible-role-rke2.git
    version: master
  - name: ansible-role-cluster-baseconfig
    src: git+git@github.com:BlindfoldedSurgery/ansible-role-cluster-baseconfig.git
    version: master
  - name: ansible-role-os-baseconfig
    src: git+git@github.com:BlindfoldedSurgery/ansible-role-os-baseconfig.git
    version: master
