---
collections:
  - name: community.general
    version: 5.6.0

roles:
  - name: ansible-role-os-baseconfig
    src: git+github.com:torbencarstens/ansible-role-os-baseconfig.git
    version: master
  - name: ansible-role-pihole
    src: git+github.com:torbencarstens/ansible-role-pihole.git
    version: master
  - name: ansible-role-pivpn
    src: git+github.com:torbencarstens/ansible-role-pivpn.git
    version: master
  - name: ansible-role-github-runner
    src: git+github.com:torbencarstens/ansible-role-github-runner.git
    version: master
