name: Workflow

on:
  push: { }
  pull_request: { }

jobs:
  validate-renovate-config:
    name: Validate Renovate configuration
    uses: BlindfoldedSurgery/renovate-config/.github/workflows/validate.yml@main

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: asdf-vm/actions/install@v2
      - run: ansible-lint --strict .